// <auto-generated />
namespace Bets.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adwaeridentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adwaeridentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201606032117087_adwaer.identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
